### PR TITLE
Using archs Query-API instead of InlineQuery. 

### PR DESCRIPTION
**Pull request by genaray**
Another small PR. Ignore the up and downgrade of archs version, there was an unexpected bug that needs to be fixed first. 
Instead of the Unsafe-Syntax we could use `chunk.GetSpan<T>` instead if that's more appropriate.

### CODE REVIEW

**Comment by friflo** [comment]
hi, will remove the <Optimize> element from debug build
 
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#optimize

**Comment by friflo** [comment]
hm, is Unsafe really necessary?

https://github.com/friflo/ECS.CSharp.Benchmark-common-use-cases?tab=readme-ov-file#setup
> The Project builds with `<AllowUnsafeBlocks>false</AllowUnsafeBlocks>`. See [ECS.Benchmark.csproj](https://github.com/friflo/ECS.CSharp.Benchmark-common-use-cases/blob/main/src/ECS.Benchmark.csproj).

**Comment by friflo** [comment]
okay - I enabled unsafe code for benchmark.
btw: Please pull latest changes before creation PR

**Comment by genaray** [comment]
Alright thanks a lot! Unsafe is not really necessary, we could use Spans instead, that should also Work. Whatever you Like more ^^

**Comment by friflo** [comment]
Removed the unsafe rule. So its fine as it is.
I didn't add the reason for this rule and cannot remember.
Maybe it was to avoid using vectorization. That requires a separate category.

**Pull request merged**
